services:
  suivi-app:
    build: .
    container_name: suivi-mode-operatoire
    ports:
      - "8080:5000"  # Port externe 8080 pour éviter les conflits
    environment:
      - FLASK_ENV=production
      - DB_SERVER=SERVEURERP
      - DB_USER=QUALITE
      - DB_PASSWORD=QUALITE
    volumes:
      - app-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app-data: 