


services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - SQL_SERVER=SERVEURERP
      - SQL_DATABASE=SEDI_ERP
      - SQL_USER=QUALITE
      - SQL_PASSWORD=QUALITE
      - AUTO_BOOTSTRAP=0
      - AUTO_EXPORT_ON_START=0
    ports:
      - "0.0.0.0:3000:3000"
    restart: unless-stopped
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:80"
    restart: unless-stopped

  dns:
    image: jpillora/dnsmasq:latest
    container_name: sedi-dns
    volumes:
      - ./dns/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    restart: unless-stopped